version: "3.9"

services:
  backend:
    image: node16:alpine
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env.development
    depends_on:
      - db
    volumes:
      - ./backend:/opt/backend
    links:
      - "db:database"

  frontend:
    image: node16
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/opt/frontend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
